change-id = 125535

[build]
target = [
    "x86_64-unknown-linux-gnu",
    "wasm32-wasmer-wasi",
    "wasm32-wasmer-wasi-dl",
]
extended = true
tools = ["cargo", "clippy", "rustfmt"]
configure-args = []

[rust]
lld = true
llvm-tools = true

[llvm]
download-ci-llvm = false

[target.wasm32-wasmer-wasi]
wasi-root = "../wasix-libc/sysroot32-eh"

[target.wasm32-wasmer-wasi-dl]
wasi-root = "../wasix-libc/sysroot32-ehpic"
